name: cloudflare-deploy-staging
on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    name: deploy to cloudflare
    runs-on: ubuntu-latest
    environment:
      name: 'Staging'
      url: dev.seiryofes.com
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: yarn run generate:stg

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages publish --project-name=quaint-app-dev dist
